services:       
  postgres_db:                         
    image: postgres    
    user: postgres        
    container_name: postgres_db
    restart: always                 
    ports:
      - "5432:5432"   
    environment:                 
      - POSTGRES_USER=${POSTGRES_USER_DOCKER}        
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DOCKER}   
      - POSTGRES_DB=${POSTGRES_DATABASE_DOCKER}       
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5  
    networks:
      - prisma-network

  app:
    build: .          
    container_name: server      
    restart: always
    ports:
      - "8080:8080"   
    tty: true  # Keeps the container running for debugging        
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER_DOCKER}:${POSTGRES_PASSWORD_DOCKER}@${POSTGRES_HOST_DOCKER}:${POSTGRES_PORT}/${POSTGRES_DATABASE_DOCKER}?schema=public 
      - SERVER_PORT=${SERVER_PORT}                     
    depends_on:
      postgres_db: 
        condition: service_healthy
    networks:
      - prisma-network

networks:
  prisma-network:
    name: prisma-network