name: Continuous integration

on:
  push:
    paths:
      - "**.ts"
      - "**.json"
      - "**.yml"
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: "Set up Docker"
        run: docker compose up -d
        env:
          POSTGRES_USER_DOCKER: ${{ vars.POSTGRES_USER_DOCKER }}
          POSTGRES_PASSWORD_DOCKER: ${{ vars.POSTGRES_PASSWORD_DOCKER }}
          POSTGRES_DATABASE_DOCKER: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          DATABASE_URL: postgresql://${{ vars.POSTGRES_USER_DOCKER }}:${{ vars.POSTGRES_PASSWORD_DOCKER }}@${{ vars.POSTGRES_HOST_DOCKER }}:${{ vars.POSTGRES_PORT }}/${{vars. POSTGRES_DATABASE_DOCKER }}?schema=public 
          SERVER_PORT: ${SERVER_PORT}
          SECRET: ${{ secrets.SECRET }}
          EXPIRES_IN: ${{ vars.EXPIRES_IN }}

      - name: Run ESLint
        run: yarn lint
